### ISSUE TITLE
Three.js demo not playing

### ISSUE THREAD

**Issue by nikolas7892** [bfred-it/iphone-inline-video#119]
It previously was working. this demo (for example) does not load the video automatically.

http://bfred-it.github.io/iphone-inline-video/demo/threejs.html

perhaps apple wants the user to have some interaction if so. would there be a way to play the video without activating the AVVideoController that takes the full screen? 

although this demo works http://bfred-it.github.io/iphone-inline-video/demo/

it doesn't support webgl.

**Comment by bfred-it** [comment]
It might have been because of non-HTTPS urls appearing in my demo. I removed them and it works.

The interaction requirement is cancelled by IIV when there is no audio.

This is a screencast on Browserstack on a real iOS 9 device. My internet connection is so slow so it's short and stuttery, but it works without interaction.

[![gif](https://fat.gfycat.com/PleasingPointlessEmperorshrimp.gif)](https://gfycat.com/PleasingPointlessEmperorshrimp)
