### ISSUE TITLE
Playing .play() twice might cause strange behavior

### ISSUE THREAD

**Issue by bfred-it** [bfred-it/iphone-inline-video#18]
Will need to prevent the second `.play()` with `if(!driver.paused) return`

**Comment by vardas-bill** [comment]
Hi Federico,

Are you aware of anyone successfully using your code in an ionic 2 project?
I can¹t get it to work in mine.

Very best,
Bill

From:  Federico Brigante <notifications@github.com>
Reply-To:  bfred-it/iphone-inline-video
<reply+008b6dbdeec868276a595a0cadeb5ab457149bf3d5edafc092cf000000011326e4789
2a169ce08d6268e@reply.github.com>
Date:  Thursday, 14 April 2016 at 05:54
To:  bfred-it/iphone-inline-video <iphone-inline-video@noreply.github.com>
Subject:  [bfred-it/iphone-inline-video] Playing .play() twice might cause
strange behavior (#18)


Will need to prevent the second .play() with if(!driver.paused) return


You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/bfred-it/iphone-inline-video/issues/18>
