### ISSUE TITLE
Onended triggers infinitely

### ISSUE THREAD

**Issue by kwadhera** [bfred-it/iphone-inline-video#61]
Using NPM iphone-inline-video@1.9.3

		document.getElementById("ele").onended = function() {
			console.log("kk");
			document.getElementById("ele").currentTime = 10; 
			document.getElementById("ele").play();
		};

It seems to loop sometimes but eventually it will stop playing and infinitely trigger ended

https://puu.sh/qraVx/1d3287f093.png

EDIT:
Commenting out

		//dispatchEventAsync(video, 'ended');
and

	       //preventEvent(video, 'ended', ಠevent, false); // prevent occasional native ended events
seems to "fix" the issue, but doing that is probably breaking other things

**Comment by bfred-it** [comment]
Thanks, I'll look into it

**Comment by bfred-it** [comment]
What is the duration of the video? It seems to me that `.play()` is again near the end when you set `currentTime = 10` so it will just loop. 

I added those two lines because the `ended` event wasn't being fired reliably for me, so [I added a fake one](https://github.com/bfred-it/iphone-inline-video/commit/b88980f52efcdaf6417f726ece8f2b55867a1a76) and [hid the native event](https://github.com/bfred-it/iphone-inline-video/commit/ac6580dc839e9bdfedec8bd513f579d3aa632b2c)
