### ISSUE TITLE
.IIV::-webkit-media-controls-play-button doesn't successfully hide the button

### ISSUE THREAD

**Issue by shisaq** [bfred-it/iphone-inline-video#72]
Hi, I tried `.IIV::-webkit-media-controls-play-button` to hide the play button, but failed;
Then I changed `.IIV` into `video`, it finally worked.
I'm a junior developer, I'm not quite sure what `.IIV` is, but I'm here just explaining `video::-webkit-media-controls-play-button` works.
Thanks for offering such a handy tool!

**Comment by bfred-it** [comment]
The `IIV` class is applied when iphone-inline-video (in short "IIV") is able to act on the element (generally on the iPhone on iOS 8-9)

I assume that you are seeing that on iOS 10, where IIV is not enabled and therefore the button is not hidden.

I hide the buttons because they cannot be fixed with IIV (i.e. They go fullscreen) but I suppose that it makes sense to document this so people know to make that change strictly for stylistic reasons.

**Comment by bfred-it** [comment]
Comment and documentation updated
