### ISSUE TITLE
iOS 10 detection doesn't work in Captive Network Assistant

### ISSUE THREAD

**Issue by shaketbaby** [bfred-it/iphone-inline-video#78]
`matchMedia('(-webkit-video-playable-inline)').matches` return false in Captive Network Assistant.

**Comment by bfred-it** [comment]
Do the videos play inline natively in there?

If yes, this only means that IIV is enabled more often than it should, which is preferrable to *not enabled when it should*

If not, it's an Apple bug. In that case, does IIV work?

**Comment by shaketbaby** [comment]
Video doesn't seem to play inline in CNA. IIV does seem to work.

**Comment by bfred-it** [comment]
From what I understand:

- `playsinline` doesn't work natively, so `matchMedia('(-webkit-video-playable-inline)').matches` rightfully returns false
- IIV is thus enabled and works

I'm not sure of where the bug is :D

**Comment by shaketbaby** [comment]
The bug is the check for iOS 10 doesn't work in CNA, which turns out to be a good thing. Just thought you might be interested in knowing this, anyway.

**Comment by bfred-it** [comment]
Ah thank you! I was confused on whether it was a bug report =)

Technically that media query specifically detects support for native inlive video playback, so it's working as expected. 

Fun fact: the query has been there since iOS 8 but was broken in iOS 9. Also barely anyone ever knew about it for the past two years :(
